#pragma once

#define IDD_SETTINGS                101

#define IDC_DEVICES                 1001
#define IDC_PORT                    1002
#define IDC_AUTORECONNECT           1003
#define IDC_AUTOSTART               1004
#define IDC_USB_ENCODE_MODE         1005
#define IDC_USB_ENCODE_PRESET       1006
#define IDC_WIFI_ENCODE_MODE        1007
#define IDC_WIFI_ENCODE_PRESET      1008
#define IDC_USB_WIFI_FAILOVER       1009
#define IDC_PICTURE_PRESET          1010
#define IDC_NEARBY                  1011
#define IDC_ADD_NEARBY              1012
#define IDC_NEARBY_HINT             1013
#define IDC_SHOW_ADVANCED           1014
#define IDC_SEPARATE_USB_WIFI       1015
#define IDC_ENCODE_BACKEND          1016
#define IDC_RESTART_ADMIN           1017
#define IDC_ADV_PORT_LABEL          1018
#define IDC_ADV_USB_LABEL           1019
#define IDC_ADV_WIFI_LABEL          1020
#define IDC_ADV_USB_MODE_LABEL      1021
#define IDC_ADV_USB_PRESET_LABEL    1022
#define IDC_ADV_WIFI_MODE_LABEL     1023
#define IDC_ADV_WIFI_PRESET_LABEL   1024
#define IDC_ADV_ENCODER_LABEL       1025
#define IDC_ADMIN_NOTE              1026
#define IDC_LEAD_HINT               1027
#define IDC_SAVED                   1028
#define IDC_REMOVE_SAVED            1029
#define IDC_ADV_MANUAL_GROUP        1030
#define IDC_ADV_MANUAL_HINT         1031
#define IDC_ADV_MANUAL_EXAMPLE      1032
#define IDC_REFRESH_NEARBY          1033
#define IDC_USB_TIP                 1034
#define IDC_SETTINGS_TABS           1035
#define IDC_NEARBY_GROUP            1036
#define IDC_SAVED_GROUP             1037
#define IDC_CONNECTION_GROUP        1038
#define IDC_QUALITY_GROUP           1039
#define IDC_QUALITY_LABEL           1040
